apimServiceName: oink-prod-001
loggers:
    - name: apim-prod
      loggerType: applicationInsights
      description: Production App Insights
      resourceId: "/subscriptions/71db92d7-5d50-4033-8937-b5d2a6102f5e/resourcegroups/lz-apps-mgmt-oink/providers/microsoft.insights/components/apim-prod"
      credentials:
        instrumentationKey: "Logger-Credentials--apim-prod"
      isBuffered: true
diagnostics:
   - name: applicationinsights
     verbosity: Error
apis:
  - name: "fin-acct-mgmt"
    diagnostics:
      - name: applicationinsights
        verbosity: Error
        loggerId: "/subscriptions/71db92d7-5d50-4033-8937-b5d2a6102f5e/resourceGroups/lz-apps-mgmt-oink/
                   providers/Microsoft.ApiManagement/service/oink-prod-001/loggers/apim-prod"
        



        
