# This is only used if demonstrating a 3 environment scenario (Dev => Staging => Prod)
apimServiceName: oink-staging-001
loggers:
    - name: apim-dev
      loggerType: applicationInsights
      description: Staging App Insights
      resourceId: "/subscriptions/71db92d7-5d50-4033-8937-b5d2a6102f5e/resourcegroups/lz-apps-mgmt-oink/providers/microsoft.insights/components/apim-staging"
      credentials:
        instrumentationKey: "Logger-Credentials--apim-staging"
      isBuffered: true
diagnostics:
   - name: applicationinsights
     verbosity: Error
     loggerId: "/subscriptions/71db92d7-5d50-4033-8937-b5d2a6102f5e/resourceGroups/lz-apps-mgmt-oink/providers/Microsoft.ApiManagement/service/oink-staging-001/loggers/apim-staging"
apis:
  - name: echo-versioned
    diagnostics:
      - name: applicationinsights
        verbosity: Error
        loggerId: "/subscriptions/71db92d7-5d50-4033-8937-b5d2a6102f5e/resourceGroups/lz-apps-mgmt-oink/providers/Microsoft.ApiManagement/service/oink-staging-001/loggers/apim-staging"



