openapi: 3.0.1
info:
  title: Financial Account Management
  version: v2
servers:
  - url: https://apim.qa.colinmac.dev/fin-account-mgmt/v2
paths:
  /accounts:
    post:
      tags:
        - admin
      summary: RequestFinancialAccountCreation
      operationId: RequestFinancialAccountCreation
      requestBody:
        description: Account information needed to create an account reference in the Oink system.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createNewFinancialAccountRequest'
            example:
              accountId: string
              accountName: string
              accountClassIdentifier: string
      responses:
        '201':
          description: Financial Account creation requested
          content:
            application/json:
              schema:
                type: string
              example: string
        '409':
          description: Financial Account creation request already exists
  '/accounts/{accountId}':
    get:
      tags:
        - financial-account
      summary: GetFinancialAccountByAccountId
      operationId: GetFinancialAccountByAccountId
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Financial Account found
          content:
            application/json:
              schema:
                type: string
              example: string
        '404':
          description: Financial Account not found
  '/accounts/{accountId}/balances':
    get:
      tags:
        - financial-account
      summary: GetFinancialAccountBalancesByAccountId
      operationId: GetFinancialAccountBalancesByAccountId
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Financial Account found
          content:
            application/json:
              schema:
                type: string
              example: string
        '404':
          description: Financial Account not found
  '/accounts/{accountId}/payments':
    get:
      tags:
        - financial-account
      summary: GetAccountPaymentsByAccountId
      operationId: GetAccountPaymentsByAccountId
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Financial Account found
          content:
            application/json:
              schema:
                type: string
              example: string
        '404':
          description: Financial Account not found
components:
  schemas:
    createNewFinancialAccountRequest:
      type: object
      properties:
        accountId:
          type: string
          format: uuid
        accountName:
          type: string
        accountClassIdentifier:
          type: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]