openapi: 3.0.1
info:
  title: Echo Versioned
  description: ''
  version: v2
servers:
  - url: https://oink-dev-001.azure-api.net/echo-v/v2
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]